#!/bin/bash

# 运行你的 command 指令
sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -vo sdl -framedrop -input  bigbuckbunny320p.mp4

# 检查 command 指令是否成功执行
if [ $? -eq 0 ]; then
    echo "Command executed successfully."
else
    echo "Command failed."
    exit 1
fi

# 运行 Python 文件
python3 /path/to/your_script.py

# 检查 Python 文件是否成功执行
if [ $? -eq 0 ]; then
    echo "Python script executed successfully."
else
    echo "Python script execution failed."
    exit 1
fi
