#!/bin/bash

sudo SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -vo sdl -framedrop –input file=/home/pi/video_fifo bigbuckbunny320p.mp4

if [ $? -eq 0 ]; then
    echo "Command executed successfully."
else
    echo "Command failed."
    exit 1
fi

# 运行 Python 文件
python video_control.py

# 检查 Python 文件是否成功执行
if [ $? -eq 0 ]; then
    echo "Python script executed successfully."
else
    echo "Python script execution failed."
    exit 1
fi
